name: Tag repo; build and publish assets
on:
  push:
    branches:
      - master

jobs:
  tag-new-version:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tag.outputs.new_version }}
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0
      - name: Bump version and push tag
        id: tag
        uses: mathieudutour/github-tag-action@v4.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: false

  build-and-publish-docker-image:
    runs-on: ubuntu-latest
    name: Build and publish docker image
    needs: tag-new-version
    if: needs.tag-new-version.outputs.tag
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Build and publish to docker registry
      uses: whoan/docker-build-with-cache-action@v5
      with:
        username: docker
        password: "${{ secrets.OPENSAFELY_DOCKER_PASSWORD }}"
        registry: docker.opensafely.org
        image_name: jupyter
        image_tag: latest,${{ needs.tag-new-version.outputs.tag }}
